// Shared country-related constants and helpers

// Phone number metadata used by booking/sign-up flows
export const COUNTRY_PHONE_MAP = [
  { name: "United States", code: "US", phone: "+1", flag: "🇺🇸" },
  { name: "Canada", code: "CA", phone: "+1", flag: "🇨🇦" },
  { name: "United Kingdom", code: "GB", phone: "+44", flag: "🇬🇧" },
  { name: "Australia", code: "AU", phone: "+61", flag: "🇦🇺" },
  { name: "Germany", code: "DE", phone: "+49", flag: "🇩🇪" },
  { name: "France", code: "FR", phone: "+33", flag: "🇫🇷" },
  { name: "Italy", code: "IT", phone: "+39", flag: "🇮🇹" },
  { name: "Spain", code: "ES", phone: "+34", flag: "🇪🇸" },
  { name: "Netherlands", code: "NL", phone: "+31", flag: "🇳🇱" },
  { name: "Sweden", code: "SE", phone: "+46", flag: "🇸🇪" },
  { name: "Norway", code: "NO", phone: "+47", flag: "🇳🇴" },
  { name: "Denmark", code: "DK", phone: "+45", flag: "🇩🇰" },
  { name: "Finland", code: "FI", phone: "+358", flag: "🇫🇮" },
  { name: "Japan", code: "JP", phone: "+81", flag: "🇯🇵" },
  { name: "South Korea", code: "KR", phone: "+82", flag: "🇰🇷" },
  { name: "Taiwan", code: "TW", phone: "+886", flag: "🇹🇼" },
  { name: "Hong Kong", code: "HK", phone: "+852", flag: "🇭🇰" },
  { name: "Singapore", code: "SG", phone: "+65", flag: "🇸🇬" },
  { name: "Thailand", code: "TH", phone: "+66", flag: "🇹🇭" },
  { name: "Malaysia", code: "MY", phone: "+60", flag: "🇲🇾" },
  { name: "Indonesia", code: "ID", phone: "+62", flag: "🇮🇩" },
  { name: "Philippines", code: "PH", phone: "+63", flag: "🇵🇭" },
  { name: "India", code: "IN", phone: "+91", flag: "🇮🇳" },
  { name: "China", code: "CN", phone: "+86", flag: "🇨🇳" },
  { name: "Brazil", code: "BR", phone: "+55", flag: "🇧🇷" },
  { name: "Mexico", code: "MX", phone: "+52", flag: "🇲🇽" },
  { name: "Argentina", code: "AR", phone: "+54", flag: "🇦🇷" },
  { name: "Chile", code: "CL", phone: "+56", flag: "🇨🇱" },
  { name: "Peru", code: "PE", phone: "+51", flag: "🇵🇪" },
  { name: "Colombia", code: "CO", phone: "+57", flag: "🇨🇴" },
  { name: "Venezuela", code: "VE", phone: "+58", flag: "🇻🇪" },
  { name: "Russia", code: "RU", phone: "+7", flag: "🇷🇺" },
  { name: "Ukraine", code: "UA", phone: "+380", flag: "🇺🇦" },
  { name: "Poland", code: "PL", phone: "+48", flag: "🇵🇱" },
  { name: "Czech Republic", code: "CZ", phone: "+420", flag: "🇨🇿" },
  { name: "Hungary", code: "HU", phone: "+36", flag: "🇭🇺" },
  { name: "Austria", code: "AT", phone: "+43", flag: "🇦🇹" },
  { name: "Switzerland", code: "CH", phone: "+41", flag: "🇨🇭" },
  { name: "Belgium", code: "BE", phone: "+32", flag: "🇧🇪" },
  { name: "Ireland", code: "IE", phone: "+353", flag: "🇮🇪" },
  { name: "Portugal", code: "PT", phone: "+351", flag: "🇵🇹" },
  { name: "Greece", code: "GR", phone: "+30", flag: "🇬🇷" },
  { name: "Turkey", code: "TR", phone: "+90", flag: "🇹🇷" },
  { name: "Israel", code: "IL", phone: "+972", flag: "🇮🇱" },
  { name: "Saudi Arabia", code: "SA", phone: "+966", flag: "🇸🇦" },
  { name: "United Arab Emirates", code: "AE", phone: "+971", flag: "🇦🇪" },
  { name: "Qatar", code: "QA", phone: "+974", flag: "🇶🇦" },
  { name: "Kuwait", code: "KW", phone: "+965", flag: "🇰🇼" },
  { name: "Bahrain", code: "BH", phone: "+973", flag: "🇧🇭" },
  { name: "Oman", code: "OM", phone: "+968", flag: "🇴🇲" },
  { name: "Egypt", code: "EG", phone: "+20", flag: "🇪🇬" },
  { name: "South Africa", code: "ZA", phone: "+27", flag: "🇿🇦" },
  { name: "Nigeria", code: "NG", phone: "+234", flag: "🇳🇬" },
  { name: "Kenya", code: "KE", phone: "+254", flag: "🇰🇪" },
  { name: "Ethiopia", code: "ET", phone: "+251", flag: "🇪🇹" },
  { name: "Ghana", code: "GH", phone: "+233", flag: "🇬🇭" },
  { name: "Morocco", code: "MA", phone: "+212", flag: "🇲🇦" },
  { name: "Tunisia", code: "TN", phone: "+216", flag: "🇹🇳" },
  { name: "Algeria", code: "DZ", phone: "+213", flag: "🇩🇿" },
  { name: "New Zealand", code: "NZ", phone: "+64", flag: "🇳🇿" },
  { name: "Fiji", code: "FJ", phone: "+679", flag: "🇫🇯" },
  { name: "Papua New Guinea", code: "PG", phone: "+675", flag: "🇵🇬" },
  { name: "Vanuatu", code: "VU", phone: "+678", flag: "🇻🇺" },
  { name: "Solomon Islands", code: "SB", phone: "+677", flag: "🇸🇧" },
  { name: "Samoa", code: "WS", phone: "+685", flag: "🇼🇸" },
  { name: "Tonga", code: "TO", phone: "+676", flag: "🇹🇴" },
  { name: "Kiribati", code: "KI", phone: "+686", flag: "🇰🇮" },
  { name: "Tuvalu", code: "TV", phone: "+688", flag: "🇹🇻" },
  { name: "Nauru", code: "NR", phone: "+674", flag: "🇳🇷" },
  { name: "Palau", code: "PW", phone: "+680", flag: "🇵🇼" },
  { name: "Marshall Islands", code: "MH", phone: "+692", flag: "🇲🇭" },
  { name: "Micronesia", code: "FM", phone: "+691", flag: "🇫🇲" },
  { name: "Afghanistan", code: "AF", phone: "+93", flag: "🇦🇫" },
  { name: "Pakistan", code: "PK", phone: "+92", flag: "🇵🇰" },
  { name: "Bangladesh", code: "BD", phone: "+880", flag: "🇧🇩" },
  { name: "Sri Lanka", code: "LK", phone: "+94", flag: "🇱🇰" },
  { name: "Nepal", code: "NP", phone: "+977", flag: "🇳🇵" },
  { name: "Bhutan", code: "BT", phone: "+975", flag: "🇧🇹" },
  { name: "Maldives", code: "MV", phone: "+960", flag: "🇲🇻" },
  { name: "Myanmar", code: "MM", phone: "+95", flag: "🇲🇲" },
  { name: "Laos", code: "LA", phone: "+856", flag: "🇱🇦" },
  { name: "Cambodia", code: "KH", phone: "+855", flag: "🇰🇭" },
  { name: "Vietnam", code: "VN", phone: "+84", flag: "🇻🇳" },
  { name: "Mongolia", code: "MN", phone: "+976", flag: "🇲🇳" },
  { name: "Kazakhstan", code: "KZ", phone: "+7", flag: "🇰🇿" },
  { name: "Uzbekistan", code: "UZ", phone: "+998", flag: "🇺🇿" },
  { name: "Kyrgyzstan", code: "KG", phone: "+996", flag: "🇰🇬" },
  { name: "Tajikistan", code: "TJ", phone: "+992", flag: "🇹🇯" },
  { name: "Turkmenistan", code: "TM", phone: "+993", flag: "🇹🇲" },
  { name: "Azerbaijan", code: "AZ", phone: "+994", flag: "🇦🇿" },
  { name: "Georgia", code: "GE", phone: "+995", flag: "🇬🇪" },
  { name: "Armenia", code: "AM", phone: "+374", flag: "🇦🇲" },
  { name: "Iran", code: "IR", phone: "+98", flag: "🇮🇷" },
  { name: "Iraq", code: "IQ", phone: "+964", flag: "🇮🇶" },
  { name: "Syria", code: "SY", phone: "+963", flag: "🇸🇾" },
  { name: "Lebanon", code: "LB", phone: "+961", flag: "🇱🇧" },
  { name: "Jordan", code: "JO", phone: "+962", flag: "🇯🇴" },
  { name: "Yemen", code: "YE", phone: "+967", flag: "🇾🇪" },
  { name: "Palestine", code: "PS", phone: "+970", flag: "🇵🇸" },
  { name: "Cyprus", code: "CY", phone: "+357", flag: "🇨🇾" },
  { name: "Malta", code: "MT", phone: "+356", flag: "🇲🇹" },
  { name: "Iceland", code: "IS", phone: "+354", flag: "🇮🇸" },
  { name: "Albania", code: "AL", phone: "+355", flag: "🇦🇱" },
  { name: "North Macedonia", code: "MK", phone: "+389", flag: "🇲🇰" },
  { name: "Serbia", code: "RS", phone: "+381", flag: "🇷🇸" },
  { name: "Montenegro", code: "ME", phone: "+382", flag: "🇲🇪" },
  { name: "Bosnia and Herzegovina", code: "BA", phone: "+387", flag: "🇧🇦" },
  { name: "Croatia", code: "HR", phone: "+385", flag: "🇭🇷" },
];

// Comprehensive country list for selects (used by forms/quiz)
export const COUNTRIES_FULL = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

// Minimal list used by lightweight forms where only major markets are needed
export const COUNTRIES_SHORT = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "South Korea",
  "Taiwan",
  "Hong Kong",
  "Singapore",
  "Thailand",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "India",
  "China",
  "Brazil",
  "Mexico",
  "Other",
];

export const getCountryCode = (countryName: string): string | null => {
  const entry = COUNTRY_PHONE_MAP.find((c) => c.name === countryName);
  return entry ? entry.code : null;
};
