-- 新規アクティビティのみをDBに追加するSQL
-- line 40以降の新規アクティビティ（83個）

begin;

insert into public.activities (slug, title, duration_minutes, location, is_active) values
  ('unlimited-photo-shoot-15min','Unlimited Photo Shoot – 15-Minute Plan (Up to 2 People)',15,'2 min walk from Shibuya 109',true),
  ('escape-impossible-real-escape-game-crossing-shibuya','Escape the Impossible – Real Escape Game at CROSSING Shibuya (90 min)',90,'3 min walk from Shibuya Station, Hachiko Exit',true),
  ('tea-flight-pairing-experience-smith-teamaker-shibuya','Tea Flight & Pairing Experience at Smith Teamaker Shibuya',45,'Shibuya Scramble Square, Direct access from Shibuya Station',true),
  ('cook-your-first-japanese-dish-beginners-class-shibuya','Cook Your First Japanese Dish – Beginner''s Class in Shibuya (90 min)',90,'5 min walk from Shibuya Station, Hachiko Exit',true),
  ('relax-with-10-gentle-samoyeds-at-tokyos-fluffiest-cafe','Relax with 10 Gentle Samoyeds at Tokyo''s Fluffiest Café',45,'5 min walk from Harajuku Station, Takeshita Exit',true),
  ('high-tech-sushi-train-dining-in-the-heart-of-shibuya','High-Tech Sushi Train Dining in the Heart of Shibuya',45,'5 min walk from Shibuya Station, Hachiko Exit',true),
  ('full-sensory-tokyo-nights-neo-chinese-food-sauna-culture-at-bunkashinka','Full-Sensory Tokyo Nights: Neo-Chinese Food, Sauna & Culture at Bunkashinka',105,'4 min walk from Shibuya Station, Hachiko Exit',true),
  ('paella-spanish-wine-pairing-at-la-bodega-shibuya','Paella & Spanish Wine Pairing at La Bodega Shibuya',90,'Direct access from Shibuya Station via Hikarie 2F Passage',true),
  ('juicy-wagyu-hamburg-sweet-french-toast-afternoon-at-shibuya-hikarie','Juicy Wagyu Hamburg & Sweet French Toast Afternoon at Shibuya Hikarie',75,'Direct access from Shibuya Station via Hikarie 2F Passage',true),
  ('luxury-shaved-ice-kakigori-tasting-at-shibuya-scramble-square','Luxury Shaved Ice (Kakigori) Tasting at Shibuya Scramble Square',30,'Direct access from Shibuya Station (inside Shibuya Scramble Square B2F)',true),
  ('design-your-own-sweet-gift-mellowhich-cube-cakes-in-shibuya','Design-Your-Own Sweet Gift: MELLOWHICH Cube Cakes in Shibuya',30,'Direct access from Shibuya Station (inside Shibuya Scramble Square 1F)',true),
  ('factory-view-chocolate-tasting-at-le-chocolat-alain-ducasse-tokyo','Factory-View Chocolate Tasting at Le Chocolat Alain Ducasse, Tokyo (45–90 min)',67,'2 min walk from Mitsukoshimae Station (Exit B6)',true),
  ('pop-art-treasure-hunt-nara-kusama-gift-curation-at-lammfromm','Pop-Art Treasure Hunt: Nara & Kusama Gift Curation at LAMMFROMM (15–40 min)',27,'Direct access from Shibuya Station (inside Shibuya Scramble Square 5F)',true),
  ('eat-japan-north-to-south-in-one-alley-shibuya-yokocho-food-fest','Eat Japan North-to-South in One Alley – Shibuya Yokocho Food & Fest (60–90 min)',75,'3 min walk from Shibuya Station (RAYARD MIYASHITA PARK South 1F)',true),
  ('japanese-whisky-spirits-tasting-kaku-uchi-base','Japanese Whisky & Spirits Tasting – KAKU-UCHI BASE (30–60 min)',45,'3 min walk from Shibuya Station (inside Shibuya Stream 1F, riverside)',true),
  ('new-style-sushi-bar-crawl-sushibuya-under-the-tracks','New-Style Sushi Bar Crawl – SUSHIBUYA Under the Tracks (60–90 min)',75,'3 min walk from Shibuya Station (inside Shibuya Stream 1F)',true),
  ('find-feel-and-take-home-tokyo-art-oil-by-bijutsu-techo','Find, Feel, and Take Home Tokyo Art – OIL by Bijutsu Techo (30–60 min)',45,'7 min walk from Shibuya Station (inside Shibuya PARCO 2F)',true),
  ('stargaze-in-shibuya-planetarium-show-at-cosmo-planetarium','Stargaze in Shibuya: Planetarium Show at Cosmo Planetarium (Self-Guided)',52,'5–7 min walk from Shibuya Station (inside Shibuya Cultural Center Owada 12F)',true),
  ('artful-nerikiri-tea-pairing-in-a-pink-hideaway','Artful Nerikiri & Tea Pairing in a Pink Hideaway (30–60 min)',45,'8–10 min walk from Yoyogi-Hachiman / Yoyogi-Koen Stations',true),
  ('60-90-minute-edomae-omakase-at-sushi-tokyo-ten-shibuya','60–90 Minute Edomae Omakase at SUSHI TOKYO TEN (Shibuya)',75,'Direct access from Shibuya Station (Shibuya Stream 3F)',true),
  ('samurai-armor-photoshoot-studio-90min-street-120min','Samurai Armor Photoshoot (Studio 90 min / Street 120 min)',105,'10 min walk from Shibuya Station',true),
  ('spin-snap-collect-2000-capsule-toys-in-the-heart-of-shibuya','Spin, Snap & Collect: 2,000+ Capsule Toys in the Heart of Shibuya (15–45 min)',30,'1 min walk from Shibuya Station (Hachikō Exit)',true),
  ('stationery-souvenir-safari-7-floor-treasure-hunt-at-shibuya-loft','Stationery & Souvenir Safari: 7-Floor Treasure Hunt at Shibuya LOFT (30–60 min)',45,'5 min walk from Shibuya Station (A3 Exit)',true),
  ('indie-bookshop-scavenger-spbs-flagship-or-scramble-square-gift-stop','Indie Bookshop Scavenger: SPBS Flagship or Scramble-Square Gift Stop (20–60 min)',40,'10 min walk from Shibuya Station (Flagship) or station-direct (Scramble Square)',true),
  ('shibuya-meat-alley-crawl','Shibuya Meat-Alley Crawl (45–90 min) — DIY Tasting Across 2 Floors',68,'Chitose Kaikan 2F, 13-8 Udagawacho, Shibuya-ku, Tokyo 150-0042, Japan',true),
  ('whisper-and-words-at-mori-no-toshoshitsu','Whisper & Words: A Self-Guided Reading Break at Mori no Toshoshitsu',60,'Shibuya Dai-ichi Kangin Kyodo Building 8F, 23-3 Udagawacho, Shibuya-ku, Tokyo 150-0042, Japan',true),
  ('shoto-museum-architecture-exhibit-dash','Shoto Museum "Architecture & Exhibit Dash" (30–60 min, self-guided)',45,'2-14-14 Shoto, Shibuya-ku, Tokyo 150-0046, Japan',true),
  ('inclusion-art-sprint-tokyo-shibuya-koen-dori-gallery','Inclusion Art Sprint at Tokyo Shibuya Koen-dori Gallery (30–60 min, self-guided)',45,'1F, Shibuya Workers'' Welfare Hall, 1-19-8 Jinnan, Shibuya-ku, Tokyo 150-0041, Japan',true),
  ('plate-and-taste-at-meals-are-delightful','Plate & Taste at MEALS ARE DELIGHTFUL — Design-Forward Lunch & Tableware Hunt (Okushibuya)',60,'1-17-5 Tomigaya, Shibuya-ku, Tokyo 151-0063, Japan',true),
  ('euro-vintage-treasure-hunt-at-amici','Euro Vintage Treasure Hunt @ AMICI (Yoyogi Park / Okushibu) — 30–60 min, self-guided',45,'Sunrise Tomigaya 102, 1-18-3 Tomigaya, Shibuya-ku, Tokyo 151-0063, Japan',true),
  ('undefeated-shibuya-drop-day-drill','UNDEFEATED Shibuya "Drop-Day Drill" — 30–90 min self-guided sneaker mission (Cat Street)',60,'S BLDG., 5-29-8 Jingumae, Shibuya-ku, Tokyo 150-0001, Japan',true),
  ('archive-hunt-at-archive-store','ARCHIVE HUNT @ ARCHIVE STORE (Shibuya–Jinnan) — 30–90 min, self-guided',60,'B1F, Wako Bldg., 1-12-16 Jinnan, Shibuya-ku, Tokyo 150-0041, Japan',true),
  ('self-guided-darts-challenge-at-bane-bagus','Self-Guided Darts Challenge @ Bane BAGUS Shibuya Miyamasuzaka (30–90 min)',60,'Kaleido Shibuya Miyamasuzaka B1–B2F, 1-12-1 Shibuya, Shibuya-ku, Tokyo 150-0002, Japan',true),
  ('design-your-relaxation-at-arona-spa','Design-Your-Relaxation: Self-Selected Massage at ARONA SPA (Shibuya)',60,'Atlas Shibuya Bldg. 5F, 30-3 Udagawacho, Shibuya-ku, Tokyo 150-0042, Japan',true),
  ('express-gel-manicure-at-fastnail-shibuya','Express Gel Manicure in Shibuya (30–75 min, design-pick & go)',52,'FPG Shibuya Miyamasu Bldg. 5F, 1-24-15 Shibuya, Shibuya-ku, Tokyo 150-0002, Japan',true),
  ('shibuya-ride-and-bite-micro-adventure-ebike','Shibuya "Ride & Bite" Micro-Adventure (15–90 min) — E-Bike Self-Guided',52,'9 Shinsencho, Shibuya-ku, Tokyo 150-0045, Japan',true),
  ('private-mini-cinema-at-gran-cyber-cafe-bagus','Private Mini-Cinema & Recharge Pod at BAGUS Shibuya (30–90 min)',60,'4F Fontis Bldg., 2-23-12 Dogenzaka, Shibuya-ku, Tokyo 150-0043, Japan',true),
  ('self-guided-junmai-sake-flight-at-yata-shibuya','Self-Guided Junmai Sake Flight at YATA Shibuya (Standing Bar, 45–60 min)',52,'5F, ILA Dogenzaka Bldg., 1-6-9 Dogenzaka, Shibuya-ku, Tokyo 150-0043, Japan',true),
  ('find-the-hidden-bar-lost-shibuya','Find-the-Hidden Bar: Signature Cocktail (or Mocktail) Sprint at LOST Shibuya',45,'2F Grand Tokyo Building, 33-1 Udagawacho, Shibuya-ku, Tokyo 150-0042, Japan',true),
  ('diy-herbarium-bottle-in-shibuya','DIY Herbarium Bottle (Flower-in-Oil) in Shibuya — 45–60 min Self-Guided Craft',52,'Sakuraoka-cho, Shibuya-ku, Tokyo 150-0031, Japan',true),
  ('mikkeller-tokyo-craft-beer-flight','Mikkeller Tokyo Craft-Beer Flight (Self-Guided, 30–60 min)',45,'2-19-11 Dogenzaka, Shibuya-ku, Tokyo 150-0043, Japan',true),
  ('purr-and-chill-cat-cafe-mocha-shibuya','Purr & Chill: Self-Guided Cat Café Time in Shibuya (MOCHA)',60,'Asortie Shibuya 8F, 32-12 Udagawacho, Shibuya-ku, Tokyo 150-0042, Japan',true),
  ('harajuku-owl-time-at-owl-village','Harajuku Owl Time: 60-Minute Hands-On Session at Owl Village',60,'4F Harajuku ATM Bldg., 1-21-15 Jingumae, Shibuya-ku, Tokyo 150-0001, Japan',true),
  ('hedgehog-hangout-at-harry-harajuku','Hedgehog Hangout in Harajuku (30–60 min)',45,'Champs-Elysees Harajuku Building 2, 4F, 1-13-21 Jingumae, Shibuya-ku, Tokyo 150-0001, Japan',true),
  ('cuddle-a-micro-pig-in-harajuku','Cuddle a Micro Pig in Harajuku',40,'1-15-4 Barbizon 76, Jingumae, Shibuya-ku, Tokyo 150-0001, Japan',true),
  ('make-your-own-ring-on-cat-street','Make-Your-Own Ring on Cat Street',70,'1F Camellia Bldg., 4-26-28 Jingumae, Shibuya-ku, Tokyo 150-0001, Japan',true),
  ('shibuya-dagashi-snack-bar-challenge','Shibuya Dagashi Snack Bar Challenge',52,'2F Ikushin Plaza Bldg., 26-5 Udagawacho, Shibuya-ku, Tokyo 150-0042, Japan',true),
  ('vinyl-listening-bar-experience-at-jbs','Vinyl-Listening Bar Experience at JBS',67,'2F Daini Takara Bldg., 1-17-10 Dogenzaka, Shibuya-ku, Tokyo 150-0043, Japan',true),
  ('silent-classical-coffee-session-at-meikyoku-kissa-lion','Silent Classical Coffee Session at Meikyoku Kissa Lion',45,'2-19-13 Dogenzaka, Shibuya-ku, Tokyo 150-0043, Japan',true),
  ('kairyou-yu-sento-reset','Kairyou-yu Sento Reset',60,'2-19-9 Higashi, Shibuya-ku, Tokyo 150-0011, Japan',true),
  ('self-guided-craft-beer-flight-at-spring-valley-brewery-tokyo','Self-Guided Craft Beer Flight at Spring Valley Brewery Tokyo',60,'13-1 Daikanyamacho, Shibuya-ku, Tokyo 150-0034, Japan',true),
  ('purr-and-chill-cat-cafe-mocha-shinjuku','Purr & Chill Cat Cafe MOCHA Shinjuku',60,'6F, Shinjuku Pegasus Building, 3-31-5 Shinjuku, Shinjuku-ku, Tokyo 160-0022, Japan',true),
  ('tokyo-cocktail-quest-at-the-sg-club','Tokyo Cocktail Quest at The SG Club',67,'1-7-8 Jinnan, Shibuya-ku, Tokyo 150-0041, Japan',true),
  ('unlimited-photo-shoot-at-picmii-shinjuku','Unlimited Photo Shoot at PICmii Shinjuku',22,'7F Kitamura Photo Equipment Store, 3-26-14 Shinjuku, Shinjuku-ku, Tokyo 160-0022, Japan',true),
  ('throw-shuriken-and-ninja-tricks-at-samurai-museum','Throw Shuriken & Ninja Tricks',40,'2-25-6 Kabukicho, Shinjuku-ku, Tokyo 160-0021, Japan',true),
  ('tokyo-rickshaw-quick-asakusa-loop','Tokyo Rickshaw Asakusa Loop',52,'1-2-1 Asakusa, Taito-ku, Tokyo 111-0032, Japan',true),
  ('express-kimono-or-samurai-studio-shoot-asakusa','Express Kimono or Samurai Studio Shoot',37,'2-2-5 Hanakawado, Taito-ku, Tokyo 111-0033, Japan',true),
  ('hands-on-owl-encounter-at-owl-cafe-oz-asakusa','Hands-On Owl Encounter at Owl Café OZ',52,'2-16-5 Asakusa, Taito-ku, Tokyo 111-0032, Japan',true),
  ('whisk-your-own-matcha-at-asakusa-chazen','Whisk-Your-Own Matcha at Asakusa Chazen',45,'1-4-7 Asakusa, Taito-ku, Tokyo 111-0032, Japan',true),
  ('kimono-mini-stroll-at-asakusa-yae','Kimono Mini-Stroll at Asakusa YAE',67,'Nakaden Building 3F, 1-2-6 Hanakawado, Taitō-ku, Tokyo 111-0033, Japan',true),
  ('pound-your-own-mochi-at-hanbei-asakusa','Pound-Your-Own Mochi at HANBEI',37,'1-15-3 Asakusa, Taito-ku, Tokyo 111-0032, Japan',true),
  ('asakusa-rickshaw-photo-ride-ebisuya','Asakusa Rickshaw Photo Ride',45,'1-34-2 Asakusa, Taito-ku, Tokyo 111-0032, Japan',true),
  ('edo-kiriko-cut-glass-workshop-asakusa-ojima','Edo Kiriko Cut-Glass Workshop',75,'4-49-7 Asakusa, Taitō-ku, Tokyo 111-0032, Japan',true),
  ('choose-your-own-asakusa-escape-game','Asakusa Escape Game',75,'1-17-2 Azumabashi, Sumida-ku, Tokyo 130-0001, Japan',true),
  ('hedgehog-night-safari-ikebukuro','Hedgehog Night Safari Ikebukuro',45,'2F, Ikebukuro Royal West, 2-35-4 Ikebukuro, Toshima-ku, Tokyo 171-0014, Japan',true),
  ('meet-and-feed-friendly-owls-at-owlpark-ikebukuro','Meet & Feed Owls at Owlpark',45,'2F, 3-30-11 Nishi-Ikebukuro, Toshima-ku, Tokyo 171-0021, Japan',true),
  ('play-like-a-local-board-game-session-at-one-ikebukuro','Board Game Session at ONE',75,'K''S II Bldg 5F/6F, 1-41-8 Nishi-Ikebukuro, Toshima-ku, Tokyo 171-0021, Japan',true),
  ('butlered-afternoon-tea-at-swallowtail-ikebukuro','Butlered Tea at Swallowtail',100,'B1F, 3-12-12 Higashi-Ikebukuro, Toshima-ku, Tokyo 170-0013, Japan',true),
  ('rabbit-time-at-usa-cafe-mimi-ikebukuro','Rabbit Time at Usa Café mimi',45,'Karakoma Dai-2 Bldg. 8F, 1-13-9 Higashi-Ikebukuro, Toshima-ku, Tokyo 170-0013, Japan',true),
  ('studio-sunseed-express-headshot','Studio SUNSEED Express Headshot',45,'2-8-17 Minami-Ikebukuro, Daini Honan Bldg. 1F, Toshima-ku, Tokyo 171-0022, Japan',true),
  ('maid-cafe-at-home-akihabara','Maid Café at-home cafe',60,'3-7F Mitsuwa Bldg., 1-11-4 Soto-Kanda, Chiyoda-ku, Tokyo 101-0021, Japan',true),
  ('owl-encounter-at-akiba-fukurou','Owl Encounter at Akiba Fukurou',60,'67 Kanda Neribei-cho, Chiyoda-ku, Tokyo 101-0022, Japan',true),
  ('akihabara-board-game-speed-session-at-jelly-jelly-cafe','Board-Game Session @ JELLY JELLY',75,'3-37-23 Kanda-Sakumacho, Chiyoda-ku, Tokyo 101-0025, Japan',true),
  ('vr-escape-room-challenge-at-reality-edge-vr','VR Escape Room Challenge',75,'3F, Magasin Kanda III, 2-2-9 Kanda-Tamacho, Chiyoda-ku, Tokyo 101-0046, Japan',true),
  ('kiuchi-whisky-micro-flight-at-tokyo-distillery','KIUCHI Whisky Micro-Flight',52,'SEEKBASE Aki-Oka Manufacture, 13-1-0-1 Kanda Neribeicho, Chiyoda-ku, Tokyo 101-0022, Japan',true),
  ('make-your-own-silver-pair-ring-in-daikanyama','Make Silver Pair Ring in Daikanyama',60,'10-4 Daikanyamacho, Shibuya-ku, Tokyo 150-0034, Japan',true),
  ('ninja-crash-course-in-harajuku','Ninja Crash-Course in Harajuku',52,'B1, 539 Bldg., 1-16-11 Jingumae, Shibuya-ku, Tokyo 150-0001, Japan',true),
  ('make-japanese-food-samples-in-asakusa','Make Japanese Food Samples',60,'3-7-6 Nishi-Asakusa, Taito-ku, Tokyo 111-0035, Japan',true),
  ('cut-your-own-edo-kiriko-glass-at-sokichi-asakusa','Cut Edo Kiriko Glass at Sokichi',90,'2-1-14 Kaminarimon, Taito-ku, Tokyo 111-0034, Japan',true),
  ('shinjuku-urban-onsen-reset-at-thermae-yu','Shinjuku Urban Onsen at Thermae-yu',75,'B1F, 1-1-2 Kabukicho, Shinjuku-ku, Tokyo 160-0021, Japan',true),
  ('all-you-can-play-bar-sprint-at-zino-shibuya','All-You-Can-Play Bar at ZINO',60,'3F, Takayama Land #15 Bldg., 28-1 Udagawacho, Shibuya-ku, Tokyo 150-0042, Japan',true),
  ('paint-your-own-japanese-teacup-and-matcha-tasting','Paint Teacup + Matcha Tasting',60,'Villa Ei 301, 2-3-23 Jingumae, Shibuya-ku, Tokyo 150-0001, Japan',true),
  ('tenq-space-museum-mini-mission-at-tokyo-dome-city','TenQ Space Museum Mini-Mission',75,'6F Yellow Bldg., 1-3-61 Koraku, Bunkyo-ku, Tokyo 112-0004, Japan',true);

commit;

